name: Build the application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: graphhopper-maps/package-lock.json
      - name: Install and build graphhopper-maps submodule
        working-directory: ./graphhopper-maps
        run: |
          cp ../config.js .
          npm install
          npm run build
      - name: Install dependencies
        run: npm install
      - name: Build node package
        run: npm run build
      - name: Create launch and splash icons
        run: npx cordova-res android --skip-config --copy
      - name: npx cap sync
        run: npx cap sync
      - name: Build the android app
        working-directory: ./android
        run: ./gradlew assembleDebug